# Setup Docker-CE for Ubuntu 16.04 LTS

---
- hosts: dockerhosts 
  remote_user: "{{ lookup('env', 'user') }}"
  become: yes
  gather_facts: no

  tasks:

  - name: Update all packages to the latest version
    apt:
      upgrade: dist

  - name: apt-get install packages
    apt:
      name: apt-transport-https,ca-certificates,curl,software-properties-common
      state: present
      update_cache: yes

  - name: Add Docker’s official GPG key
    apt_key:
      url: "https://download.docker.com/linux/ubuntu/gpg"
      state: present
    register: set_key

  # $ lsb_release -cs
  # xenial
  - name: set up the stable repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present
    when: set_key

  - name: Install docker-ce
    apt: 
      name: docker-ce
      state: present
      update_cache: yes
